---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'pbdrc'

# Adjust the quality of the generated images when they are resized
ImagickBackend:
  default_quality: 90

# Produce resampled output
Image:
  force_resample: true

# Extending the Siteconfig Activation
SiteConfig:
  extensions:
    - SiteConfigExtension

# GoogleMapField
GoogleMapField:
  default_options:
    api_key: AIzaSyANE7wlfv9Vo17LyngDxPAQrEswJJDzwVg